spring.application.name=books

# ✅ Mostrar SQL no console
spring.jpa.show-sql=true

# ✅ Swagger
springdoc.api-docs.path=/api-docs

# ✅ BANCO H2 (OBRIGATÓRIO NA PROVA)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ✅ JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# ✅ Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console